# Unit test and general code health!!!

In [1]:
import numpy as np

import grogupy
import grogupy.viz

# insulator eset 100
# insulator esetp 600

# metallic eset 1000
# metallic esetp 10000

# 100 kpoint for diatomic systems

[Daniels-MacBook-Air.local:94792] shmem: mmap: an error occurred while determining whether or not /var/folders/yh/dx7xl94n3g52ts3td8qcxjcc0000gn/T//ompi.Daniels-MacBook-Air.501/jf.0/3850764288/sm_segment.Daniels-MacBook-Air.501.e5860000.0 could be created.
/Users/danielpozsar/Documents/oktatás/elte/phd/grogu/.venv/lib/python3.9/site-packages/grogupy/_tqdm.py:24: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm


In [2]:
infile = "../benchmarks/Fe_colinear/Fe.fdf"
# infile = "../benchmarks/Cr3/Cr3.fdf"
# infile = "/Users/danielpozsar/Downloads/Fe3GeTe2/Fe3GeTe2.fdf"

In [3]:
simulation_kspace = grogupy.Kspace([1, 1, 1])
simulation_kspace.plot().show()
simulation_kspace

<grogupy.Kspace kset=[1 1 1], NK=1>

In [4]:
simulation_contour = grogupy.Contour(
    eset=100,
    esetp=10000,
    emin=None,
    emax=0,
    emin_shift=-5,
    emax_shift=0,
    eigfile=infile,
)
simulation_contour.plot().show()
simulation_contour

<grogupy.Contour emin=-13.414990000000001, emax=0, eset=100, esetp=10000>

In [5]:
simulation_hamiltonian = grogupy.Hamiltonian(
    infile,
    [0, 0, 1],
)

Calculate H_XC: 100%|██████████| 3/3 [00:00<00:00, 126.48it/s]


In [6]:
xyz = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

simulation = grogupy.Builder(xyz, matlabmode=True)

simulation.add_kspace(simulation_kspace)
simulation.add_contour(simulation_contour)
simulation.add_hamiltonian(simulation_hamiltonian)
simulation.ref_xcf_orientations

/Users/danielpozsar/Documents/oktatás/elte/phd/grogu/.venv/lib/python3.9/site-packages/grogupy/physics/builder.py:258: UserWarning:

Matlabmode is used, the exchange field reference directions were set to x,y,z!



[{'o': array([1, 0, 0]),
  'vw': [array([0, 1, 0]),
   array([0, 0, 1]),
   array([0.        , 0.70710678, 0.70710678])]},
 {'o': array([0, 1, 0]),
  'vw': [array([1, 0, 0]),
   array([0, 0, 1]),
   array([0.70710678, 0.        , 0.70710678])]},
 {'o': array([0, 0, 1]),
  'vw': [array([1, 0, 0]),
   array([0, 1, 0]),
   array([0.70710678, 0.70710678, 0.        ])]}]

In [7]:
magnetic_entities = [
    dict(atom=0, l=2),
    dict(atom=1, l=2),
    dict(atom=2, l=2),
]
simulation.add_magnetic_entities(magnetic_entities)
simulation.magnetic_entities

Add magnetic entities::   0%|          | 0/3 [00:00<?, ?it/s]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
pairs = [
    dict(ai=0, aj=1, Ruc=np.array([0, 0, 0])),
    dict(ai=1, aj=2, Ruc=np.array([0, 0, 0])),
    dict(ai=2, aj=0, Ruc=np.array([0, 0, 0])),
]
simulation.add_pairs(pairs)
simulation.pairs

In [ ]:
simulation.solve()

In [ ]:
print(simulation.to_magnopy())

In [ ]:
K_fit = []
K_calc = []
K_cons = []
for mag_ent in simulation.magnetic_entities:
    mag_ent.fit_anisotropy_tensor(simulation.ref_xcf_orientations)
    K_fit.append(mag_ent.K_meV)
    mag_ent.calculate_anisotropy()
    K_calc.append(mag_ent.K_meV)
    K_cons.append(mag_ent.K_consistency_meV)

K_fit = np.array(K_fit)
K_calc = np.array(K_calc)


J_fit = []
D_fit = []
S_fit = []
J_calc = []
D_calc = []
S_calc = []
for pair in simulation.pairs:
    pair.fit_exchange_tensor(simulation.ref_xcf_orientations)
    J_fit.append(pair.J_meV)
    D_fit.append(pair.D_meV)
    S_fit.append(pair.J_S_meV)
    pair.calculate_exchange_tensor()
    J_calc.append(pair.J_meV)
    D_calc.append(pair.D_meV)
    S_calc.append(pair.J_S_meV)

J_fit = np.array(J_fit)
J_calc = np.array(J_calc)
D_fit = np.array(D_fit)
D_calc = np.array(D_calc)
S_fit = np.array(S_fit)
S_calc = np.array(S_calc)

In [ ]:
xyz = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

simulation_2 = grogupy.Builder(xyz, matlabmode=False)

simulation_2.add_kspace(simulation_kspace)
simulation_2.add_contour(simulation_contour)
simulation_2.add_hamiltonian(simulation_hamiltonian)
simulation_2.add_magnetic_entities(magnetic_entities)
simulation_2.add_pairs(pairs)
simulation_2.pairs
simulation_2.solve()

J_fit_2 = []
D_fit_2 = []
S_fit_2 = []
for pair in simulation_2.pairs:
    pair.fit_exchange_tensor(simulation_2.ref_xcf_orientations)
    J_fit_2.append(pair.J_meV)
    D_fit_2.append(pair.D_meV)
    S_fit_2.append(pair.J_S_meV)

J_fit_2 = np.array(J_fit_2)
D_fit_2 = np.array(D_fit_2)
S_fit_2 = np.array(S_fit_2)

K_fit_2 = []
for mag_ent in simulation_2.magnetic_entities:
    mag_ent.fit_anisotropy_tensor(simulation_2.ref_xcf_orientations)
    K_fit_2.append(mag_ent.K_meV)
K_fit_2 = np.array(K_fit_2)

In [ ]:
xyz = np.array(
    [
        [np.cos(np.pi / 3), np.sin(np.pi / 3), 0],
        [np.cos(2 * np.pi / 3), np.sin(2 * np.pi / 3), 0],
        [1, 0, 0],
        # [0, 1, 0],
        # [0, 0, 1],
    ]
)

simulation_3 = grogupy.Builder(xyz)

simulation_3.add_kspace(simulation_kspace)
simulation_3.add_contour(simulation_contour)
simulation_3.add_hamiltonian(simulation_hamiltonian)
simulation_3.add_magnetic_entities(magnetic_entities)
simulation_3.add_pairs(pairs)
simulation_3.solve()

J_fit_3 = []
D_fit_3 = []
S_fit_3 = []
for pair in simulation_3.pairs:
    pair.fit_exchange_tensor(simulation_3.ref_xcf_orientations)
    J_fit_3.append(pair.J_meV)
    D_fit_3.append(pair.D_meV)
    S_fit_3.append(pair.J_S_meV)

J_fit_3 = np.array(J_fit_3)
D_fit_3 = np.array(D_fit_3)
S_fit_3 = np.array(S_fit_3)

K_fit_3 = []
for mag_ent in simulation_3.magnetic_entities:
    mag_ent.fit_anisotropy_tensor(simulation_3.ref_xcf_orientations)
    K_fit_3.append(mag_ent.K_meV)
K_fit_3 = np.array(K_fit_3)

In [ ]:
rounding = 3
K_cons = np.around(K_cons, rounding)

J_calc = np.around(J_calc, rounding)
D_calc = np.around(D_calc, rounding)
S_calc = np.around(S_calc, rounding)
K_calc = np.around(K_calc, rounding)


J_fit = np.around(J_fit, rounding)
D_fit = np.around(D_fit, rounding)
S_fit = np.around(S_fit, rounding)
K_fit = np.around(K_fit, rounding)

J_fit_2 = np.around(J_fit_2, rounding)
D_fit_2 = np.around(D_fit_2, rounding)
S_fit_2 = np.around(S_fit_2, rounding)
K_fit_2 = np.around(K_fit_2, rounding)

J_fit_3 = np.around(J_fit_3, rounding)
D_fit_3 = np.around(D_fit_3, rounding)
S_fit_3 = np.around(S_fit_3, rounding)
K_fit_3 = np.around(K_fit_3, rounding)

In [ ]:
print("K_cons should be zero")
K_cons

In [ ]:
print("J_fit, J_calc")
print((J_fit == J_calc).all())
print("K_fit, K_calc")
print((K_fit == K_calc).all())
print()
print("J_fit, J_fit2")
print((J_fit == J_fit_2).all())
print("K_fit, K_fit2")
print((K_fit == K_fit_2).all())
print()
print("J_fit, J_fit3")
print((J_fit == J_fit_3).all())
print("K_fit, K_fit3")
print((K_fit == K_fit_3).all())

In [ ]:
print("Off diagonal part is equal")
print("D_fit, D_calc")
print((D_fit == D_calc).all())
print()
print("S_fit, S_calc")
print((S_fit == S_calc).all())
print()
print("Jfit, Jcalc")
print(J_fit[:, 0, 0])
print(J_calc[:, 0, 0])
print()
print(J_fit[:, 1, 1])
print(J_calc[:, 1, 1])
print()
print(J_fit[:, 2, 2])
print(J_calc[:, 2, 2])

In [ ]:
print("K_fit, K_calc")
print(K_fit[:, 0, 0])
print(K_calc[:, 0, 0])
print()
print(K_fit[:, 1, 1])
print(K_calc[:, 1, 1])
print()
print(K_fit[:, 0, 1])
print(K_calc[:, 0, 1])
print()
print(K_fit[:, 0, 2])
print(K_calc[:, 0, 2])
print()
print(K_fit[:, 1, 2])
print(K_calc[:, 1, 2])

In [ ]:
print("Off diagonal part is equal")
print("D_fit, D_fit_3")
print((D_fit == D_fit_3).all())
print()
print("S_fit, S_fit_3")
print((S_fit == S_fit_3).all())
print()
print("J_fit, J_fit_3")
print(J_fit[:, 0, 0])
print(J_fit_3[:, 0, 0])
print()
print(J_fit[:, 1, 1])
print(J_fit_3[:, 1, 1])
print()
print(J_fit[:, 2, 2])
print(J_fit_3[:, 2, 2])

In [ ]:
print("K_fit, K_fit_3")
print(K_fit[:, 0, 0])
print(K_fit_3[:, 0, 0])
print()
print(K_fit[:, 1, 1])
print(K_fit_3[:, 1, 1])
print()
print(K_fit[:, 0, 1])
print(K_fit_3[:, 0, 1])
print()
print(K_fit[:, 0, 2])
print(K_fit_3[:, 0, 2])
print()
print(K_fit[:, 1, 2])
print(K_fit_3[:, 1, 2])

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

r = R.from_rotvec(np.pi / 2 * np.array([0, 0, 1]))
r.as_matrix()

In [ ]:
grogupy.save(simulation, "test_builder.pkl", compress=0)
grogupy.save(simulation.contour, "test_contour.pkl", compress=0)
grogupy.save(simulation.kspace, "test_kspace.pkl", compress=0)
grogupy.save(simulation.pairs[0], "test_pair.pkl", compress=0)
grogupy.save(simulation.magnetic_entities[0], "test_magnetic_entity.pkl", compress=0)

In [ ]:
simulation._dh.S_idx