# Calculate magnetic parameters

grogupy is specifically written in a modular way, to fully take advantage of python classes. In this simple example we show how to use grogupy to simulate the magnetic interaction between two atoms from a density functional theory (DFT) calculation and create an output file for [magnopy](https://docs.magnopy.org/en/latest/user-guide/start/about.html). In this example we will use a non-collinear Siesta calculation of the Fe3GeTe2 system.

First import ``grogupy``, which will import the most important classes, functions and variables in its namespace. Then import ``numpy`` for data manipulation.

In [1]:
import grogupy

/Users/danielpozsar/Documents/oktatás/elte/phd/grogupy_project/.venv/lib/python3.9/site-packages/grogupy/__init__.py:48: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm as _tqdm
[Daniels-MacBook-Air.local:25126] shmem: mmap: an error occurred while determining whether or not /var/folders/yh/dx7xl94n3g52ts3td8qcxjcc0000gn/T//ompi.Daniels-MacBook-Air.501/jf.0/806879232/sm_segment.Daniels-MacBook-Air.501.30180000.0 could be created.


Then we start to create the basic classes based on the desired parameters. First create the ``Kspace`` class which contains the parameters fot the Brillouin zone integration. Because in this case we only take a single layer of Fe3GeTe2 and there is a large vacuum in the perpendicular direction it is sufficient to only 
integrate in the plane of the material. Furthermore for a fast initial calculation a 10x10 grid of k-points should be enough.

In [2]:
Fe3GeTe2_kspace = grogupy.Kspace(kset=[10, 10, 1])
Fe3GeTe2_kspace

<grogupy.Kspace kset=[10 10  1], NK=100>

Then we would like to set the parameters for the complex integral for the Green's 
function calculation. This can be done through the ``Contour`` class. Again, for an 
initial calculation 300 sample points should be enough. The energy minimum should be 
set below the smallest eigenvalue from the Siesta Hamiltonian.


In [3]:
Fe3GeTe2_contour = grogupy.Contour(emin=-15, eset=300, esetp=10000)
Fe3GeTe2_contour

<grogupy.Contour emin=-20, emax=0, eset=300, esetp=10000>

Then we can create the ``Hamiltonian`` class, which extracts and stores the Hamiltonian 
and geometrical data from the Siesta files using the ``sisl`` library. Furthermore we must 
provide the exchange field orientation in the DFT calculation, which is usually the 
perpendicular direction from the 2D material.


In [4]:
Fe3GeTe2_hamiltonian = grogupy.Hamiltonian(
    infile="/Users/danielpozsar/Downloads/nojij/Fe3GeTe2/monolayer/soc/lat3_791/Fe3GeTe2.fdf",
    scf_xcf_orientation=[0, 0, 1],
)
Fe3GeTe2_hamiltonian

Calculate H_XC: 100%|██████████| 3/3 [00:00<00:00, 74.85it/s]


<grogupy.Hamiltonian scf_xcf_orientation=[0 0 1], orientation=[0, 0, 1], NO=84>

After these initial steps we can create the ``Builder`` class and initialize with the 
above information. We have to provide the directions of the rotated exchange field and the 
two perpendicular directions are calculated automatically.


In [5]:
orientations = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

Fe3GeTe2 = grogupy.Builder(ref_xcf_orientations=orientations)
Fe3GeTe2.add_kspace(Fe3GeTe2_kspace)
Fe3GeTe2.add_contour(Fe3GeTe2_contour)
Fe3GeTe2.add_hamiltonian(Fe3GeTe2_hamiltonian)
Fe3GeTe2

<grogupy.Builder npairs=0, numk=100, kset=[10 10  1], eset=300>

Then we have to define the magnetic entities, which can be a list of orbitals from the 
Siesta Hamiltonian. We use ``sisl`` functions to extract this information based on a more 
human like definition. For example take two shells from two Fe atoms.


In [6]:
magnetic_entities = [dict(atom=3, l=2), dict(atom=4, l=2)]

With this information we can create two ``MagneticEntity`` instances.


In [7]:
magnetic_entities = Fe3GeTe2.create_magnetic_entities(magnetic_entities)
Fe3GeTe2.add_magnetic_entities(magnetic_entities)

Add magnetic entities:: 100%|██████████| 2/2 [00:00<00:00, 42799.02it/s]


This would be enough to calculate the anisotropy on both sites, but it is not 
enough to build a spin model, for this we need the exchange tensor between all the pairs. 
Generally this can be done in a very similar way. First a list of dictionaries must be 
created, where each dictionary contains ``ai``, ``aj`` and ``Ruc``, where the first two is the 
index from the magnetic_entities and the third is the supercell shift of the second 
magnetic entity.


In [8]:
pairs = [
    dict(ai=0, aj=1, Ruc=[0, 0, 0]),
    dict(ai=0, aj=1, Ruc=[1, 0, 0]),
]
pairs = Fe3GeTe2.create_pairs(pairs)
Fe3GeTe2.add_pairs(pairs)
Fe3GeTe2

Add pairs:: 100%|██████████| 2/2 [00:00<00:00, 15033.35it/s]


<grogupy.Builder npairs=2, numk=100, kset=[10 10  1], eset=300>

Now every information is contained in the Fe3GeTe2 instance to run the simulation. 
There are multiple parameters that can be changed to tune the runtime and the precision 
of the simulation, but for now let us use the default parameters.

In [9]:
Fe3GeTe2.solve()

Parallel over k: 100%|██████████| 100/100 [02:19<00:00,  1.40s/it]
/Users/danielpozsar/Documents/oktatás/elte/phd/grogupy_project/.venv/lib/python3.9/site-packages/grogupy/physics/magnetism.py:607: UserWarning: Still not sure about the -2!
  warnings.warn("Still not sure about the -2!")


Now the instance parameters are filled with the data from the simulation, so we can 
output the information. We can print the instance ``Fe3GeTe2`` to get the information of 
the run and the ``to_magnopy()`` method returns the results in ``magnopy``'s input format.


In [10]:
print(Fe3GeTe2)

grogupy version: 1.0.0
Input file: /Users/danielpozsar/Downloads/nojij/Fe3GeTe2/monolayer/soc/lat3_791/Fe3GeTe2.fdf
SLURM job ID: Could not be determined.
Architecture: CPU
Number of nodes in the parallel cluster: 1
Parallelization is over: K
Solver used for Greens function calculation: Sequential
Solver used for Exchange tensor: Fit
Solver used for Anisotropy tensor: Fit
Cell [Ang]:
3.791001511088653242e+00 0.000000000000000000e+00 0.000000000000000000e+00
-1.895500755544326621e+00 3.283103614407953064e+00 0.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00 2.057000819825037041e+01
DFT axis: [0 0 1]
Quantization axis and perpendicular rotation directions:
[1. 0. 0.] --> [array([ 0.,  0., -1.]), array([0., 1., 0.])]
[0. 1. 0.] --> [array([1., 0., 0.]), array([ 0.,  0., -1.])]
[0. 0. 1.] --> [array([1., 0., 0.]), array([0., 1., 0.])]
Parameters for the Brillouin zone sampling:
Number of k points: 100
K points in each directions: [10 10  1]
Parameters for the conto

In [11]:
print(Fe3GeTe2.to_magnopy(comments=False))

cell Angstrom
3.791001511088653242e+00 0.000000000000000000e+00 0.000000000000000000e+00
-1.895500755544326621e+00 3.283103614407953064e+00 0.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00 2.057000819825037041e+01
atoms Angstrom
name	x	y	z	Sx	Sy	Sz	# Q
3Fe(l:2) -7.339158738013707e-06 4.149278510690423e-06 11.657585837928032 0.0001210526102417882 -7.743363827228948e-05 1.9986027351384723 # 7.0230961409775094
4Fe(l:2) -7.326987662162937e-06 4.158274523275774e-06 8.912422537596708 -0.00012111332265951005 7.748113247885768e-05 1.9986076327496851 # 7.023095375773057
notation
double-counting True
spin-normalized True
exchange-factor 0.5
on-site-factor 1
exchange meV
--------------------------------------------------------------------------------
3Fe(l:2) 4Fe(l:2) 0 0 0 # distance [Ang]: 2.745163300331324
isotropic -84.46273037354347
DMI 0.18861406406170206 -0.0007640169986298999 -4.377855715127648e-07 # Dx Dy Dz
symmetric-anisotropy 2.383115192979659 2.4004206864026

More information can be found in the Tutorials.